### PR TITLE
Configuration for common i18n strings

### PR DESCRIPTION
**Pull request by andre8244**
Added configuration for `common.json`

NethServer/dev#6206

### CODE REVIEW

**Review by DavidePrincipi — COMMENTED** [review]
It seems this PR introduces a big change in the way translations are managed. One of the basic assumptions is: one package, one .json file.

Do you have any alternative solutions?

**Comment by andre8244** [comment]
> It seems this PR introduces a big change in the way translations are managed. One of the basic assumptions is: one package, one .json file.
> 
> Do you have any alternative solutions?

Having a centralized place where most common strings are mantained can have advantages (e.g. avoid repetition inside every module and a singole place to change, if needed) but it's not essential.
An alternative solution is not doing anything at all :)

**Comment by gsanchietti** [comment]
> An alternative solution is not doing anything at all :)

I like such simple plans! :grin:

**Comment by DavidePrincipi** [comment]
Ok for the "common" strings to reduce the pressure on translators... However I wouldn't change the single file assumption. I'm afraid there is too much work around it. 

As alternative we could merge the common and specific parts here (a `jq` script might do the job), during the RPM build. This approach surely has a limitation in the  development phase: some strings might result untranslated until nethserver-lang is released :thinking:

In the end, if the "common" strings are in a small number, we can cut/paste them in each package without any change here...

**Comment by gsanchietti** [comment]
I agree with @DavidePrincipi : we are introducing a bunch of new code just to handle a corner case.
Also the jq approach could be a good one if we do not want to modify all existing packages.

Let's see what @filippocarletti think about it

**Comment by filippocarletti** [comment]
Unfortunately, the user request to modify the suffixes came too late in the development cycle.
I'd evaluate again the request for a future version.

**Pull request closed without merging**
