### PR TITLE
Cockpit UI builds

### PR DESCRIPTION
**Pull request by DavidePrincipi**
Add translations for Cockpit-based applications.

As example, add nethserver.CockpitMail catalog

### CODE REVIEW

**Review by gsanchietti — CHANGES_REQUESTED** [review]
Before merge, we should also add the following resources:

- CockpitFirewall (after nethserver/nethserver-firewall-base#92 has been completed)
- CockpitCore (after nethserver/nethserver-cockpit#80 has been completed)

**Comment by DavidePrincipi** [comment]
Ok please add them to `./tx/config`

**Comment by gsanchietti** [comment]
> Ok please add them to `./tx/config`

You already did it at least for the firewall, I can't do it for the core until all the refactor work is complete.

**Comment by gsanchietti** [comment]
Merging it as is, I will add firewall and core files as soon as all other PR has been merged.

**Review by gsanchietti — APPROVED** [review]

**Pull request merged**
