### PR TITLE
Create NethServer_Module_ddclient.rst

### PR DESCRIPTION
**Pull request by jgjimenez**
Create NethServer_Module_ddclient.rst

### CODE REVIEW

**Comment by jgjimenez** [comment]
Create NethServer_Module_ddclient.rst

**Comment by DavidePrincipi** [comment]
@jgjimenez , this PR contains a lot of commits that were already merged. I opened a new PR #8 with a single commit: is it the right one? Is there any other commit to merge?

**Comment by jgjimenez** [comment]
HI Davide,

Only this for now.

Regards.

**Comment by gsanchietti** [comment]
Cherry-picked.

**Pull request closed without merging**
